[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
fory-derive.workspace = true
fory-core.workspace = true
bytes.workspace = true
server = { path = "../server" }
serde = { version = "1.0.228", features = ["derive"] }
bincode2 = "2.0.1"